# Generated by Django 4.1.1 on 2022-09-19 15:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('eventCode', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=300)),
                ('dateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=100)),
                ('isAcceptingQuestions', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionText', models.TextField()),
                ('dateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdBy', models.CharField(default='Anonymous', max_length=100)),
                ('eventCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainQA.event')),
            ],
        ),
    ]
