# Generated by Django 4.1.1 on 2022-09-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainQA', '0002_event_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
