# Generated by Django 4.1.1 on 2022-10-07 01:05

from django.db import migrations, models
import mainQA.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainQA', '0003_alter_event_datecreated_alter_question_datecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventCode',
            field=models.CharField(default=mainQA.models.ec_gen, max_length=6),
        ),
    ]
