# Generated by Django 4.1.1 on 2022-10-07 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainQA', '0004_alter_event_eventcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='eventCode',
            new_name='eventId',
        ),
    ]
