# Generated by Django 4.1.1 on 2022-10-07 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainQA', '0005_rename_eventcode_question_eventid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='eventId',
            new_name='parentEvent',
        ),
    ]
