# Generated by Django 4.1.1 on 2022-10-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainQA', '0006_rename_eventid_question_parentevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='desc',
            field=models.CharField(default='', max_length=300),
        ),
    ]
